### ISSUE TITLE
Bibtex Export

### ISSUE THREAD

**Issue by amackcrane** [cgxeiji/scholar#3]
Hi Eiji & others,

Been really enjoying using & tinkering with scholar! I'm typesetting something using bibtex and noticing that 'scholar export' doesn't output the all field names that bibtex wants -- e.g. journals and dates don't show up because of 'journaltitle' vs 'journal' and 'date' vs. 'year'. From a quick google, my understanding is that the [bibtex .bib database format](https://en.wikipedia.org/wiki/BibTeX#Bibliographic_information_file) is standard across bibtex, biblatex/biber, and similar. If I'm right about that, some simple changes to Entry.Bib() might do the trick (unless it made sense to change the Entry object itself), and I could work up a PR.

cheers,
Austen

**Comment by cgxeiji** [comment]
Hi Austen,

I'm glad `scholar` has been useful to you! You are right, the way `export` works now is not compatible with `bibtex`, only `biblatex`. This is mainly because I need to use `biblatex` for Japanese support in my research.

According to the [biblatex manual](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf):
> **year field (literal)**
>     The year of publication. This field is a literal field only when given explicitly in
>     the data (for plain BibTeX compatibility for example). It is however better to use
>     the date field as this is compatible with plain years too and supports many more
>     features. See §§ 2.3.8 and 2.3.9.

Likewise, `journal` is not a registered entry on `biblatex`, so it would break compatibility with `biblatex`. Sadly, `.bib` format is not standard across the different implementations.

I think it should be pretty straight forward to create a new exported function `entry.BibTex() string` and add an optional flag to the `export` command to export in `bibtex` format. Nonetheless, the default output would be `biblatex`.

Another solution is to change your template file (located at `$HOME/.config/scholar/types.yaml`) and add the field that you need for `bibtex`. You may remove `journaltitle` and change it with `journal`. You can also add a `year` field, although the `date` field should stay because it is used to parse other elements (like generate the authoryear key).

Doing this won't update the entries you already have, you will need to edit the entries manually.

Let me know what you think!

**Comment by amackcrane** [comment]
Thanks, that makes me less confused, I just hadn't found the right biblatex documentation. It's good to know some of the types.yaml dependencies. Given that, adding a `--bibtex` flag and `entry.BibTex()` makes good sense, I'll see about implementing that!

**Comment by cgxeiji** [comment]
Added the option to export to `bibtex` with `scholar export --format=bibtex`. If you have the opportunity to use it, let me know if it is working correctly.

Thank you!
